### PR TITLE
Several bug fixes

### PR DESCRIPTION
**Pull request by lav45**
- Fix $this->dataProvider->getPagination()->getPage()
- Fix getFromDataProvider() for iteration

### CODE REVIEW

**Comment by lav45** [comment]
In Yii2 found a bug https://github.com/yiisoft/yii2/pull/8180

**Comment by xjflyttp** [comment]
yiisoft/yii2#8180
because dataProvider is lazyLoad 
$totalCount will set by BaseDataProvider->getTotalCount()
dataProvider->getModels() will active prepareTotalCount() 

this problem in Yii1 is exist. 

You can call $dataProvider->prepare(); before totalCount、getPage、etc...

``` php
        $_GET['page'] = 2;

        $dataProvider = new ArrayDataProvider([
            'allModels' => [
                ['id' => 1],
                ['id' => 2],
                ['id' => 3],
                ['id' => 4],
                ['id' => 5],
                ['id' => 6],
                ['id' => 7],
            ],
            'pagination' => [
                'pageSize' => 1,
            ],
        ]);

        //init
        $dataProvider->prepare();

        var_dump($dataProvider->getPagination()->getPage());
        // return => int 2

        var_dump($dataProvider->getModels());
        // return => array (size=2)
        //  0 => 
        //    array (size=1)
        //      'id' => int 1
        //  1 => 
        //    array (size=1)
        //      'id' => int 2
```

**Comment by lav45** [comment]
Well, let's wait until someone not fixed your bug.

**Comment by LAV45** [comment]
:-1:

**Comment by xjflyttp** [comment]
I'm say to you reason... 
why did you ? 
You are so funny....

**Pull request closed without merging**
